name: sport_stats_live
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  get_it: ^7.2.0

  # data dependencies
  uuid: ^3.0.5
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # domain dependencies
  flutter_bloc: 7.3.0
  equatable: ^2.0.3

  # presentation dependencies:
  dotted_border: ^2.0.0+1
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  modal_bottom_sheet: ^2.0.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  image_path_android: "assets/graphics/launcher/launcher.png"
  image_path_ios: "assets/graphics/launcher/launcher.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^1.8.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/graphics/logos/
    - assets/graphics/icons/
    - assets/graphics/launcher/
    - assets/graphics/sport_icons/
    - google_fonts/