name: sport_stats_live
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^2.1.0
  flutter_bloc: 7.3.0
  uuid: ^3.0.5
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  sticky_grouped_list: ^2.0.0-nullsafety.2

  # presentation dependencies:
  dotted_border: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^1.8.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
